### ISSUE TITLE
false output when using next option

### ISSUE THREAD

**Issue by ThePoolGuyRAFL** [asnakep/ScheduledBlocks#7]
Hi there, I use this fantastic tool as it's much lighter on my node, but recently when I use the next option it has given me false information. on 2 occasions the next option stated we had a block assigned but when I run it again during the epoch using the current option it states I dont have a block assigned.

I'm not sure if this is updated anymore but id love if this tool could be maintained for the upcoming Vasil fork etc

**Comment by asnakep** [comment]
Hello,

sorry for delay, I faced this issue only once, when Cardano Foundation left the pool due to drop of active stake.
I try to explain, I checked next epoch blocks with about 15Mil ADA of active stake and got 14 assigned blocks.
Then on new epoch I checked once again, and got no scheduled block.
Is the only case I faced. But I've heard other people facing the same.

I simplified the script to only check schedules for current epoch, since Armada Alliance is no longer providing the next epoch
nonce API, which came from cncli.

If I can found some spare time I will develop a mechanism to get new epoch nonce.
Very busy with Emurgo Academy.

I also added instructions for a proper libsodium installation.

I'm pleased you like this tool.

Thank you
kind regards,
Manuel
